version: "3.9"

services:

  redis:
    image: redis:alpine
    container_name: redis_container

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    container_name: postgres_container

  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    image: django:app
    depends_on:
      - db
    container_name: django_container
